version: '1'
services:
  clustered-data-warehouse:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=clustered_data_warehouse
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0000
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306